import 'dotenv/config';
import http from 'node:http';
import { ActionRowBuilder, ButtonBuilder, ButtonStyle, Client, EmbedBuilder, GatewayIntentBits, ModalBuilder, PermissionFlagsBits, SlashCommandBuilder, StringSelectMenuBuilder, TextInputBuilder, TextInputStyle } from 'discord.js';
import { createClient } from '@supabase/supabase-js';

const required=['DISCORD_BOT_TOKEN','DISCORD_GUILD_ID','SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY'];
const missing=required.filter(k=>!process.env[k]);
if(missing.length){console.error(`Fehlende Einstellungen: ${missing.join(', ')}`);process.exit(1)}
const discord=new Client({intents:[GatewayIntentBits.Guilds]});
const supabase=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const colors={rank_change:0xefbf61,appointment_created:0x62db8b,vote_created:0x6fa8ff,vote_ended:0xd8b76c};
const choices=['ja','nein','enthaltung'];
const pendingEvidence=new Map();

function clean(value,fallback='–',limit=1000){const t=String(value??'').trim();return t?t.slice(0,limit):fallback}
function channelFor(type){if(type==='rank_change')return process.env.DISCORD_UPRANK_CHANNEL_ID||process.env.DISCORD_DEFAULT_CHANNEL_ID;if(type==='appointment_created')return process.env.DISCORD_APPOINTMENT_CHANNEL_ID||process.env.DISCORD_DEFAULT_CHANNEL_ID;if(type.startsWith('vote_'))return process.env.DISCORD_VOTE_CHANNEL_ID||process.env.DISCORD_DEFAULT_CHANNEL_ID;return process.env.DISCORD_DEFAULT_CHANNEL_ID}
function employeePing(type,channel){if(!['appointment_created','vote_created'].includes(type))return{};const configuredId=process.env.DISCORD_EMPLOYEE_ROLE_ID;const role=configuredId?channel.guild?.roles.cache.get(configuredId):channel.guild?.roles.cache.find(r=>r.name.toLowerCase().includes('mitarbeiter'));const roleId=role?.id||configuredId;if(!roleId)return{};return{content:`<@&${roleId}>`,allowedMentions:{roles:[roleId]}}}
function formatDate(date,time=''){if(!date)return'Nicht angegeben';const d=new Date(`${date}T${time||'00:00'}`);if(Number.isNaN(d.getTime()))return clean([date,time].filter(Boolean).join(' '));const o={day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Europe/Berlin'};if(time)Object.assign(o,{hour:'2-digit',minute:'2-digit'});return d.toLocaleString('de-DE',o)}

function standardEmbed(event){const p=event.payload||{};const e=new EmbedBuilder().setColor(colors[event.event_type]||0xefbf61).setFooter({text:'Retro Ranger UCP'}).setTimestamp(new Date(event.created_at));if(event.event_type==='rank_change')return e.setTitle('⭐ Ranger-Rang geändert').setDescription(`**${clean(p.display_name,'Ranger')}** wurde im UCP aktualisiert.`).addFields({name:'Vorher',value:clean(p.old_rank,'Kein Rang'),inline:true},{name:'Jetzt',value:clean(p.new_rank,'Kein Rang'),inline:true});if(event.event_type==='appointment_created')return e.setTitle('📅 Neuer Ranger-Termin').setDescription(clean(p.beschreibung,'Ein neuer Termin wurde im UCP eingetragen.')).addFields({name:'Termin',value:clean(p.titel)},{name:'Datum / Uhrzeit',value:formatDate(p.datum,p.uhrzeit),inline:true},{name:'Ort',value:clean(p.ort),inline:true});if(event.event_type==='vote_ended')return e.setTitle('✅ Ranger-Rat-Abstimmung beendet').setDescription(`**${clean(p.titel,'Abstimmung')}** wurde im UCP beendet.`);return e.setTitle('Ranger-UCP-Ereignis').setDescription(clean(JSON.stringify(p)))}
function voteButtons(id,disabled=false){return[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`vote:${id}:ja`).setLabel('Ja').setEmoji('✅').setStyle(ButtonStyle.Success).setDisabled(disabled),new ButtonBuilder().setCustomId(`vote:${id}:nein`).setLabel('Nein').setEmoji('❌').setStyle(ButtonStyle.Danger).setDisabled(disabled),new ButtonBuilder().setCustomId(`vote:${id}:enthaltung`).setLabel('Enthaltung').setEmoji('➖').setStyle(ButtonStyle.Secondary).setDisabled(disabled))]}
async function loadVote(id){const[{data:vote,error:ve},{data:ballots,error:be}]=await Promise.all([supabase.from('ucp_rat_abstimmungen').select('*').eq('id',id).maybeSingle(),supabase.from('ucp_rat_stimmen').select('stimme').eq('abstimmung_id',id)]);if(ve)throw ve;if(be)throw be;return{vote,ballots:ballots||[]}}
function voteMessage(vote,ballots=[]){const c={ja:0,nein:0,enthaltung:0};for(const b of ballots)if(choices.includes(b.stimme))c[b.stimme]++;const ended=vote.status==='beendet'||(vote.endet_am&&new Date(vote.endet_am)<=new Date());const e=new EmbedBuilder().setColor(ended?colors.vote_ended:colors.vote_created).setTitle(ended?'✅ Abstimmung beendet':'🗳️ Neue Ranger-Rat-Abstimmung').setDescription(clean(vote.beschreibung,'Stimme direkt über die Buttons ab. Deine Auswahl wird ins UCP übertragen.')).addFields({name:'Thema',value:clean(vote.titel)},{name:'Ja',value:String(c.ja),inline:true},{name:'Nein',value:String(c.nein),inline:true},{name:'Enthaltung',value:String(c.enthaltung),inline:true},{name:'Ende',value:vote.endet_am?new Date(vote.endet_am).toLocaleString('de-DE',{timeZone:'Europe/Berlin'}):'Kein Enddatum'}).setFooter({text:ended?'Abstimmung geschlossen · Retro Ranger UCP':'Discord und UCP sind synchronisiert'});return{embeds:[e],components:voteButtons(vote.id,ended)}}
async function rememberVote(id,channelId,messageId){const{error}=await supabase.from('ucp_bot_vote_messages').upsert({abstimmung_id:id,channel_id:channelId,message_id:messageId,updated_at:new Date().toISOString()},{onConflict:'abstimmung_id'});if(error)throw error}
async function refreshVote(id){const[{vote,ballots},{data:link,error}]=await Promise.all([loadVote(id),supabase.from('ucp_bot_vote_messages').select('*').eq('abstimmung_id',id).maybeSingle()]);if(error)throw error;if(!vote||!link)return;const channel=await discord.channels.fetch(link.channel_id).catch(()=>null);if(!channel?.isTextBased())return;const message=await channel.messages.fetch(link.message_id).catch(()=>null);if(message)await message.edit(voteMessage(vote,ballots))}

async function sendEvent(event){if(event.event_type==='vote_tally_changed'){await refreshVote(event.payload?.abstimmung_id);return}const id=channelFor(event.event_type);if(!id)throw new Error(`Kein Discord-Kanal für ${event.event_type} konfiguriert.`);const channel=await discord.channels.fetch(id).catch(()=>null);if(!channel?.isTextBased())throw new Error(`Kanal ${id} nicht gefunden.`);if(event.event_type==='vote_created'){const{vote,ballots}=await loadVote(event.payload?.id);if(!vote)return;const m=await channel.send({...voteMessage(vote,ballots),...employeePing(event.event_type,channel)});await rememberVote(vote.id,channel.id,m.id);return}if(event.event_type==='vote_ended'){await refreshVote(event.payload?.id);await channel.send({embeds:[standardEmbed(event)]});return}await channel.send({embeds:[standardEmbed(event)],...employeePing(event.event_type,channel)})}
let polling=false;
async function processEvents(){if(polling||!discord.isReady())return;polling=true;try{const{data,error}=await supabase.from('ucp_bot_events').select('*').is('processed_at',null).order('created_at',{ascending:true}).limit(20);if(error)throw error;for(const event of data||[]){try{await sendEvent(event);const{error:e}=await supabase.from('ucp_bot_events').update({processed_at:new Date().toISOString()}).eq('id',event.id);if(e)throw e}catch(err){console.error(`Ereignis ${event.id} fehlgeschlagen:`,err.message)}}}catch(err){console.error('Ereignisverarbeitung fehlgeschlagen:',err.message)}finally{polling=false}}

function evidenceCommand(){const c=new SlashCommandBuilder().setName('tv').setDescription('Nimmt einen Tatverdächtigen mit Beweisen auf').addAttachmentOption(o=>o.setName('personalausweis').setDescription('Screenshot des Personalausweises').setRequired(true));for(let i=1;i<=5;i++)c.addAttachmentOption(o=>o.setName(`beweisfoto_${i}`).setDescription(`Weiteres Beweisfoto ${i} (optional)`));return c}
async function registerCommands(){const guild=await discord.guilds.fetch(process.env.DISCORD_GUILD_ID);await guild.commands.set([new SlashCommandBuilder().setName('ranger-status').setDescription('Prüft die Verbindung des Ranger-UCP-Bots').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).toJSON(),evidenceCommand().toJSON()])}
function canUseEvidence(i){const role=process.env.DISCORD_RANGER_ROLE_ID;return!role||i.memberPermissions?.has(PermissionFlagsBits.ManageMessages)||i.member?.roles?.cache?.has(role)}
function selectOptions(values,selected){return values.map(value=>({label:value,value,default:value===selected}))}
function evidenceSelectionMessage(pending){const ready=Boolean(pending.waffenlizenz&&pending.waffenstufe&&pending.fuehrerschein);const embed=new EmbedBuilder().setColor(0xefbf61).setTitle('🚓 Tatverdächtigen aufnehmen – Schritt 1/2').addFields(
  {name:'🔫 Waffenlizenz',value:clean(pending.waffenlizenz,'Noch auswählen'),inline:true},
  {name:'🎯 Höchste Waffenstufe',value:clean(pending.waffenstufe,'Noch auswählen'),inline:true},
  {name:'🪪 Führerschein',value:clean(pending.fuehrerschein,'Noch auswählen'),inline:true},
  {name:'Zusatzinformation',value:`${pending.files.length} Anhang/Anhänge angehängt`,inline:false}
).setDescription('Triff deine Auswahl und klicke anschließend auf **Weiter →**.');return{embeds:[embed],components:[
  new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('tv-select-license').setPlaceholder('Waffenlizenz auswählen …').addOptions(selectOptions(['Vorhanden','Entzogen','Nicht vorhanden'],pending.waffenlizenz))),
  new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('tv-select-level').setPlaceholder('Höchste Waffenstufe auswählen …').addOptions(selectOptions(['Keine','Stufe 1','Stufe 2','Stufe 3'],pending.waffenstufe))),
  new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('tv-select-driver').setPlaceholder('Führerschein auswählen …').addOptions(selectOptions(['Vorhanden','Entzogen','Nicht vorhanden'],pending.fuehrerschein))),
  new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tv-continue').setLabel('Weiter →').setStyle(ButtonStyle.Primary).setDisabled(!ready))
]}}
function evidenceModal(){return new ModalBuilder().setCustomId('tv-details').setTitle('TV aufnehmen · Schritt 2/2').addComponents(
  new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('tv_name').setLabel('Name').setPlaceholder('Vor- und Nachname des TV').setStyle(TextInputStyle.Short).setMaxLength(100).setRequired(true)),
  new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('geburtsdatum').setLabel('Geburtsdatum').setPlaceholder('TT.MM.JJJJ').setStyle(TextInputStyle.Short).setMaxLength(30).setRequired(true)),
  new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('rechte').setLabel('Rechte verlesen von / Zeuge').setPlaceholder('Verleser und Zeuge angeben').setStyle(TextInputStyle.Paragraph).setMaxLength(500).setRequired(true)),
  new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('beschlagnahmt').setLabel('Gegenstände beschlagnahmt').setPlaceholder('Ein Gegenstand pro Zeile').setStyle(TextInputStyle.Paragraph).setMaxLength(1000).setRequired(false)),
  new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('rueckgabe').setLabel('Gegenstände Rückgabe').setPlaceholder('Ein Gegenstand pro Zeile').setStyle(TextInputStyle.Paragraph).setMaxLength(1000).setRequired(false))
)}
async function handleEvidence(i){if(!canUseEvidence(i)){await i.reply({content:'Du hast keine Berechtigung für die Beweissicherung.',ephemeral:true});return}const files=[i.options.getAttachment('personalausweis')];for(let n=1;n<=5;n++){const a=i.options.getAttachment(`beweisfoto_${n}`);if(a)files.push(a)}const pending={files:files.map(a=>({url:a.url,name:a.name})),waffenlizenz:null,waffenstufe:null,fuehrerschein:null,createdAt:Date.now()};pendingEvidence.set(`${i.guildId}:${i.user.id}`,pending);await i.reply({ephemeral:true,...evidenceSelectionMessage(pending)})}
async function handleEvidenceSelect(i){const key=`${i.guildId}:${i.user.id}`;const pending=pendingEvidence.get(key);if(!pending||Date.now()-pending.createdAt>15*60*1000){pendingEvidence.delete(key);await i.reply({content:'Der Vorgang ist abgelaufen. Bitte führe `/tv` erneut aus.',ephemeral:true});return}if(i.customId==='tv-select-license')pending.waffenlizenz=i.values[0];if(i.customId==='tv-select-level')pending.waffenstufe=i.values[0];if(i.customId==='tv-select-driver')pending.fuehrerschein=i.values[0];pendingEvidence.set(key,pending);await i.update(evidenceSelectionMessage(pending))}
async function continueEvidence(i){const pending=pendingEvidence.get(`${i.guildId}:${i.user.id}`);if(!pending||Date.now()-pending.createdAt>15*60*1000){await i.reply({content:'Der Vorgang ist abgelaufen. Bitte führe `/tv` erneut aus.',ephemeral:true});return}if(!pending.waffenlizenz||!pending.waffenstufe||!pending.fuehrerschein){await i.reply({content:'Bitte wähle zuerst Waffenlizenz, Waffenstufe und Führerschein aus.',ephemeral:true});return}await i.showModal(evidenceModal())}
async function finishEvidence(i){const key=`${i.guildId}:${i.user.id}`;const pending=pendingEvidence.get(key);if(!pending||Date.now()-pending.createdAt>15*60*1000){pendingEvidence.delete(key);await i.reply({content:'Der Vorgang ist abgelaufen. Bitte führe `/tv` erneut aus.',ephemeral:true});return}await i.deferReply({ephemeral:true});const cid=process.env.DISCORD_EVIDENCE_CHANNEL_ID;const channel=cid?await discord.channels.fetch(cid).catch(()=>null):i.channel;if(!channel?.isTextBased()){await i.editReply('Der Beweiskanal wurde nicht gefunden.');return}const tvName=i.fields.getTextInputValue('tv_name');const geburtsdatum=i.fields.getTextInputValue('geburtsdatum');const rechte=i.fields.getTextInputValue('rechte');const beschlagnahmt=i.fields.getTextInputValue('beschlagnahmt');const rueckgabe=i.fields.getTextInputValue('rueckgabe');const embed=new EmbedBuilder().setColor(0xefbf61).setTitle('🚓 Tatverdächtiger aufgenommen').addFields({name:'👤 Name',value:clean(tvName),inline:true},{name:'🎂 Geburtsdatum',value:clean(geburtsdatum),inline:true},{name:'🔫 Waffenlizenz',value:clean(pending.waffenlizenz),inline:true},{name:'🎯 Höchste Waffenstufe',value:clean(pending.waffenstufe),inline:true},{name:'🪪 Führerschein',value:clean(pending.fuehrerschein),inline:true},{name:'⚖️ Rechte verlesen von / Zeuge',value:clean(rechte),inline:false},{name:'📥 Gegenstände beschlagnahmt',value:clean(beschlagnahmt,'Nichts'),inline:false},{name:'📤 Gegenstände Rückgabe',value:clean(rueckgabe,'Nichts'),inline:false},{name:'📄 Zusatzinformation',value:`Aufgenommen von <@${i.user.id}>`,inline:false},{name:'Beweisdateien',value:String(pending.files.length),inline:true}).setTimestamp().setFooter({text:'Retro Ranger · Beweissicherung'});try{await channel.send({embeds:[embed],files:pending.files.map((a,index)=>({attachment:a.url,name:index===0?`personalausweis-${a.name}`:a.name}))});pendingEvidence.delete(key);await i.editReply(`Tatverdächtiger wurde in <#${channel.id}> aufgenommen.`)}catch(err){console.error('Beweissicherung fehlgeschlagen:',err.message);await i.editReply(`Beweissicherung fehlgeschlagen: ${clean(err.message)}`)}}
async function handleVote(i){const[,id,choice]=i.customId.split(':');if(!choices.includes(choice))return;await i.deferReply({ephemeral:true});try{const{vote}=await loadVote(id);if(!vote||vote.status==='beendet'||(vote.endet_am&&new Date(vote.endet_am)<=new Date())){await i.editReply('Diese Abstimmung ist bereits beendet.');await refreshVote(id);return}const{data:user,error:ue}=await supabase.from('ucp_users').select('id,enabled').eq('discord_id',i.user.id).eq('enabled',true).maybeSingle();if(ue)throw ue;if(!user){await i.editReply('Dein Discord-Konto ist noch nicht mit einem freigeschalteten UCP-Konto verbunden.');return}const{error}=await supabase.from('ucp_rat_stimmen').upsert({abstimmung_id:id,user_id:user.id,stimme:choice},{onConflict:'abstimmung_id,user_id'});if(error)throw error;await refreshVote(id);await i.editReply(`Deine Stimme **${choice==='enthaltung'?'Enthaltung':choice.toUpperCase()}** wurde gespeichert und ins UCP übertragen.`)}catch(err){console.error('Abstimmung fehlgeschlagen:',err.message);await i.editReply(`Abstimmen fehlgeschlagen: ${clean(err.message)}`)}}

discord.once('ready',async()=>{console.log(`Ranger-Bot online als ${discord.user.tag}`);try{await registerCommands();console.log('Slash-Commands registriert.')}catch(e){console.error('Slash-Commands fehlgeschlagen:',e.message)}await processEvents();setInterval(processEvents,Math.max(10,Number(process.env.POLL_INTERVAL_SECONDS)||15)*1000)});
discord.on('interactionCreate',async i=>{if(i.isButton()&&i.customId.startsWith('vote:'))return handleVote(i);if(i.isStringSelectMenu()&&i.customId.startsWith('tv-select-'))return handleEvidenceSelect(i);if(i.isButton()&&i.customId==='tv-continue')return continueEvidence(i);if(i.isModalSubmit()&&i.customId==='tv-details')return finishEvidence(i);if(!i.isChatInputCommand())return;if(i.commandName==='tv')return handleEvidence(i);if(i.commandName!=='ranger-status')return;const{error}=await supabase.from('ucp_bot_events').select('id',{count:'exact',head:true});await i.reply({ephemeral:true,embeds:[new EmbedBuilder().setColor(error?0xe05d5d:0x62db8b).setTitle(error?'⚠️ Verbindung unvollständig':'✅ Ranger-Bot funktioniert').setDescription(error?`Supabase meldet: ${clean(error.message)}`:'Discord, Supabase und die Synchronisierung sind verbunden.')]})});
const port=Number(process.env.PORT)||3000;http.createServer((_q,r)=>{r.writeHead(200,{'Content-Type':'application/json'});r.end(JSON.stringify({ok:true,botReady:discord.isReady()}))}).listen(port,()=>console.log(`Healthcheck auf Port ${port}`));
discord.login(process.env.DISCORD_BOT_TOKEN);
process.on('unhandledRejection',e=>console.error('Unbehandelter Fehler:',e));
